In [26]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns

In [27]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [28]:
missing_values=['NAN','NaN','Nan',"na",np.nan,"None","NA"]
x=pd.read_csv('/content/gdrive/My Drive/ML data sets /House price /train.csv')
y=pd.read_csv('/content/gdrive/My Drive/ML data sets /House price /test.csv')
dataset=pd.concat([x,y],axis=0)
dataset.shape

(2919, 81)

In [29]:
dataset = dataset.set_index("Id")

In [30]:
# list of numerical variables
numerical_features = [feature for feature in dataset.columns if dataset[feature].dtypes != 'O']

print('Number of numerical variables: ', len(numerical_features))

# visualise the numerical variables

Number of numerical variables:  37

In [31]:
#replacing values with 0 for numerical variables
dataset['LotFrontage'].fillna(0,inplace = True)
dataset['GarageYrBlt'].fillna(0,inplace = True)
dataset['MasVnrArea'].fillna(0,inplace = True)
dataset['BsmtFullBath'].fillna(0,inplace = True)
dataset['BsmtHalfBath'].fillna(0,inplace = True)
dataset['TotalBsmtSF'].fillna(0,inplace = True)
dataset['BsmtUnfSF'].fillna(0,inplace = True)
dataset['GarageArea'].fillna(0,inplace = True)
dataset['GarageCars'].fillna(0,inplace = True)
dataset['BsmtFinSF2'].fillna(0,inplace = True)
dataset['BsmtFinSF1'].fillna(0,inplace = True)

In [32]:
# list of variables that contain year information
year_feature = [feature for feature in numerical_features if 'Yr' in feature or 'Year' in feature]

year_feature

['YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'YrSold']

In [33]:
categorical_features=[feature for feature in dataset.columns if dataset[feature].dtypes=='O']
categorical_features

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [34]:
#replacing missing values with 0 

replace_na=['MiscFeature','Alley','FireplaceQu','GarageCond','GarageQual','GarageFinish','GarageType',	
'BsmtExposure','BsmtFinType2','BsmtFinType1','MSZoning','PoolQC','BsmtQual','BsmtCond','MasVnrType',
'Utilities','Functional','Exterior2nd','Electrical',
'KitchenQual','Exterior1st','SaleType','Fence']
for i in replace_na:
  dataset[i].fillna('Miss',inplace = True)

In [35]:
dataset[categorical_features].columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [36]:
skewed_features = ['1stFlrSF',
 '2ndFlrSF',
 '3SsnPorch',
 'BedroomAbvGr',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtFullBath',
 'BsmtHalfBath',
 'BsmtUnfSF',
 'EnclosedPorch',
 'Fireplaces',
 'FullBath',
 'GarageArea',
 'GarageCars',
 'GrLivArea',
 'HalfBath',
 'KitchenAbvGr',
 'LotArea',
 'LotFrontage',
 'LowQualFinSF',
 'MasVnrArea',
 'MiscVal',
 'OpenPorchSF',
 'PoolArea',
 'ScreenPorch',
 'TotRmsAbvGrd',
 'TotalBsmtSF',
 'WoodDeckSF']

In [37]:
# decrease the skewnwnes of the data
for i in skewed_features:
    dataset[i] = np.log(dataset[i] + 1)

In [38]:
SalePrice = np.log(x['SalePrice'] + 1)

In [39]:
# Creating list of all the values which have to be used as  Dummy Variables 
dummy_list=['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition']

In [40]:
dummy_drop = []
clean_df = dataset
for i in dummy_list:
    dummy_drop += [i + '_' + str(dataset[i].unique()[-1])]

dataset = pd.get_dummies(dataset, columns = dummy_list)
dataset = dataset.drop(dummy_drop, axis = 1)

In [41]:
# removing -infy values from datafram 
dataset.replace([np.inf, -np.inf], np.nan).dropna(axis=0)

      MSSubClass  LotFrontage  ...  SaleCondition_Normal  SaleCondition_Partial
Id                             ...
1             60     4.189655  ...                     1                      0
2             20     4.394449  ...                     1                      0
3             60     4.234107  ...                     1                      0
4             70     4.110874  ...                     0                      0
5             60     4.442651  ...                     1                      0
...          ...          ...  ...                   ...                    ...
1456          60     4.143135  ...                     1                      0
1457          20     4.454347  ...                     1                      0
1458          70     4.204693  ...                     1                      0
1459          20     4.234107  ...                     1                      0
1460          20     4.330733  ...                     1                      0

[1460 rows x 269 columns]

In [43]:
train_len = len(x)
X_train = dataset[:train_len]
X_test = dataset[train_len:]
y_train = SalePrice

print(X_train.shape)
print(X_test.shape)
print(len(y_train))

(1460, 269)
(1459, 269)
1460

In [44]:
X_train=X_train.drop(['SalePrice'],axis=1)

In [45]:
X_test.drop(['SalePrice'],axis=1,inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [46]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import make_scorer, r2_score

def test_model(model, X_train=X_train, y_train=y_train):
    cv = KFold(n_splits = 3, shuffle=True, random_state = 45)
    r2 = make_scorer(r2_score)
    r2_val_score = cross_val_score(model, X_train, y_train, cv=cv, scoring = r2)
    score = [r2_val_score.mean()]
    return score

In [47]:
from sklearn.svm import SVR
svr_reg = SVR(kernel='rbf')
test_model(svr_reg)

[0.26292776617404606]

In [48]:
import sklearn.linear_model as linear_model
LR = linear_model.LinearRegression()
test_model(LR)

[0.8399460856230263]

In [49]:
rdg = linear_model.Ridge()
test_model(rdg)

[0.882191637544537]

In [52]:
svr_reg.fit(X_train,y_train)
y_pred = np.exp(svr_reg.predict(X_test)).round(2)

In [53]:
y_pred

array([156974.07, 155426.18, 179176.05, ..., 164143.99, 107822.75,
       176680.07])